spring.application.name=task-platform

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa@123

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# REDIS CONFIG
# ===============================
spring.cache.type=simple
# If Redis is running, use below instead:
# spring.redis.host=localhost
# spring.redis.port=6379
# spring.cache.type=redis

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=MyVeryStrongSecretKeyForJWTAuthentication123456
jwt.expiration=86400000

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.smarttask=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE